# Site settings
title: Homepage for Ted Laderas, PhD
email: laderast@ohsu.edu
description: Professional Website for Ted Laderas, Postdoc at OHSU Knight Cancer Institute
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://laderast.github.io" # the base hostname & protocol for your site
twitter_username: tladeras
github_username:  laderast
# Build settings
markdown: kramdown

theme: jekyll-theme-minimal